server:
  port: ${PORT:8080}

spring:
  application:
    name: ms-api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          use-framework-retry-filter: true
          routes:
            - id: ms-gestion-academica
              uri: ${GESTION_ACADEMICA_URI:http://localhost:8081}
              predicates:
                - Path=/api/alumnos/**,/api/alumnosCurso/**,/api/asignaturas/**,/api/cargas-academicas/**,/api/cursos/**,/api/evaluaciones/**,/api/notas/**,/api/usuarios/**
              filters:
                - Retry=2

cors:
  allowed-origins: http://localhost:5173